### ISSUE TITLE
Show quests as a List and on map

### ISSUE THREAD

**Issue by exilhanseat** [masterofchi/PokemonBotMap#12]
SQL-Statement is taken from MAD:
For references see:
https://github.com/Map-A-Droid/MAD/blob/master/madmin/templates/map.html
https://github.com/Map-A-Droid/MAD/blob/master/utils/questGen.py
https://github.com/Map-A-Droid/MAD/blob/master/madmin/madmin.py (Line 554)

**Comment by masterofchi** [comment]
done with https://github.com/masterofchi/PokemonBotMap/pull/16

**Comment by masterofchi** [comment]
released with https://github.com/exilhanseat/PokemonBotMap/pull/19
